name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Dependencies
      run: |
        sudo echo "deb http://packages.wand.net.nz trusty main" | sudo tee -a /etc/apt/sources.list
        sudo curl https://packages.wand.net.nz/keyring.gpg -o /etc/apt/trusted.gpg.d/wand.gpg
        sudo apt update
        sudo apt -y install autoconf automake libtool git libpcap-dev libtrace4 libtrace4-dev libprotoident libprotoident-dev liblinear3 liblinear-dev
        git clone --branch 3.2-stable https://github.com/ntop/nDPI/ /tmp/nDPI
        cd /tmp/nDPI && ./autogen.sh && ./configure && make && sudo make install && cd -

    - name: Build
      run: go build -v ./...

    - name: Lint/Vet
      run: |
        go vet ./...
        golint ./...

    - name: Test
      run: go test -v ./...
